<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="17.505" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2025-03-05T12:55:10" tests="0" file="cypress/e2e/secondTest.spec.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Testing log out" timestamp="2025-03-05T12:55:10" tests="1" time="17.498" failures="1">
    <testcase name="Testing log out Verify user can log out successfully" time="5.424" classname="Verify user can log out successfully">
      <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign up1&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign up1'
    at Context.eval (webpack://real-world-app/./cypress/e2e/secondTest.spec.js:13:26)]]></failure>
    </testcase>
  </testsuite>
</testsuites>